"use client";

import React, { useState } from "react";
import { CaptionSegment, useCaptions } from "./utils";

export default function AICaptionGenerator() {
  const { selectedVideo, setCaptions } = useCaptions();
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    if (!selectedVideo) {
      alert("Choose a video first.");
      return;
    }

    setIsGenerating(true);
    try {
      // TODO: Replace this with real AI call (Cloudflare Workers AI / Whisper).
      const generated = fakeGenerateFromVideo(selectedVideo.id);
      setCaptions(generated);
    } catch (err) {
      console.error(err);
      alert("Failed to generate captions. See console for details.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="flex flex-col gap-2">
      <span className="text-sm font-semibold text-yellow-300">
        AI Caption Generator
      </span>
      <button
        type="button"
        onClick={handleGenerate}
        disabled={isGenerating}
        className="px-3 py-1 rounded-full bg-[#FFD700] text-[#7B0F24] text-sm font-semibold hover:brightness-110 disabled:opacity-60"
      >
        {isGenerating ? "Generating…" : "Auto-generate captions"}
      </button>
      <span className="text-[11px] text-yellow-200">
        (Stubbed: uses demo captions now. We’ll wire real AI next.)
      </span>
    </div>
  );
}

// simple fake generator so you can see everything wired up
function fakeGenerateFromVideo(videoId: string): CaptionSegment[] {
  const baseText = [
    "Welcome to Integrity Streaming.",
    "This is a demo caption generated by AI.",
    "Later we will use real speech-to-text here.",
    "You can edit, move and sync these captions.",
    "Save them and reuse from the Editor.",
  ];

  const segments: CaptionSegment[] = [];
  let t = 0;
  for (let i = 0; i < baseText.length; i++) {
    const start = t;
    const end = t + 3.5;
    t = end + 0.2;

    segments.push({
      id: `ai-${videoId}-${i}`,
      start,
      end,
      text: baseText[i],
    });
  }
  return segments;
}
